
var GLOBAL=function(){var issetCallstack=function(name,lib){if(lib.changeCallstack[name]){var i=0;len=lib.changeCallstack[name].length;for(;i<len;i++){if(is(lib.changeCallstack[name][i],'Function')){lib.changeCallstack[name][i](lib.var[name]);}}}}
var lib={var:{},changeCallstack:{},get:function(name){return this.var[name];},set:function(name,value){this.var[name]=value;issetCallstack(name,this);return this;},unset:function(name){delete this.var[name];issetCallstack(name,this);return this;},watch:function(name,callstack){if(this.changeCallstack[name]){this.changeCallstack[name].push(callstack);}else{this.changeCallstack[name]=[callstack];}
return this.changeCallstack[name].length-1;},unwatch:function(name,id){if(this.changeCallstack[name]){this.changeCallstack[name][id]=false;}
return true;}};return lib;}();var LIB=function(){var tagsToReplace={'&':'&amp;','<':'&lt;','>':'&gt;'};return{escapeHtml:function(str){var div=document.createElement('div');div.appendChild(document.createTextNode(str));return div.innerHTML;},unescapeHtml:function(escapedStr){var div=document.createElement('div');div.innerHTML=escapedStr;var child=div.childNodes[0];return child?child.nodeValue:'';}};}();function is(el,type){var clas=Object.prototype.toString.call(el).slice(8,-1);return el!==undefined&&el!==null&&clas===type;}
function inArray(array,needle){return!!array.filter(function(item){return item==needle}).length}
function doGetCaretPosition(ctrl){'use strict';var CaretPos=0,Sel;if(document.selection){Sel=document.selection.createRange();ctrl.focus();Sel.moveStart('character',-ctrl.value.length);CaretPos=Sel.text.length;}else if(ctrl.selectionStart||ctrl.selectionStart==='0'){CaretPos=ctrl.selectionStart;}
return(CaretPos);};function setCaretPosition(ctrl,pos){'use strict';if(ctrl.setSelectionRange){ctrl.focus();ctrl.setSelectionRange(pos,pos);}else if(ctrl.createTextRange){var range=ctrl.createTextRange();range.collapse(true);range.moveEnd('character',pos);range.moveStart('character',pos);range.select();}};function getChar(event){'use strict';if(event.which===null){if(event.keyCode<32){return null;}
return String.fromCharCode(event.keyCode);}
if(event.which!==0&&event.charCode!==0){if(event.which<32){return null;}
return String.fromCharCode(event.which);}
return null;};function dump(list){var result=[],dampRec=function(list,delim){var i,pr=delim,probel='&#160;&#160;&#160;';if(is(list,'Object')){result.push('Object { ');pr=delim+probel;}else if(is(list,'Array')){result.push('Array { ');pr=delim+probel;}
for(i in list){if(is(list[i],'Object'||is(list[i],'Array'))){result.push('\n'+pr);result.push(pr+i+' : ')
dampRec(list[i],pr+probel);}else{result.push('\n'+pr+i+': '+list[i])}}
if(is(list,'Object')||is(list,'Array')){result.push('\n'+delim+' }');}}
dampRec(list,'');return result.join('');}
(function(){'use strict';var element='[isNumber], [isEn], [isRu], [isEmpty]';LIB.validate=function(element){var value=element.value,isNumber=element.hasAttribute('isNumber'),isEn=element.hasAttribute('isEn'),isRu=element.hasAttribute('isRu'),isEmpty=element.hasAttribute('isEmpty'),is=true;if(isNumber&&!/^[0-9]$/.test(value)){is=false;}
if(isEn&&/[а-яёА-ЯЁ]/.test(value)){is=false;}
if(isRu&&/[a-zA-Z]/.test(value)){is=false;}
if(isEmpty&&value.length<1){is=false;}
return is};$(document).on('input',element,function(){if(LIB.validate(this)){$(this).removeClass('invalid');}else{$(this).addClass('invalid');}}).on('blur',element,function(){var value=this.value,isEmpty=this.hasAttribute('isEmpty');if(isEmpty&&value===''){$(this).addClass('invalid');}else if(value===''){$(this).removeClass('invalid');}});}());(function(){'use strict';var element='[tsanslateCHPU], [onlyNumbers], [onlyRu], [onlyEn]',lib={onlyNumbers:function(e){e=e||event;if(e.ctrlKey||e.altKey||e.metaKey){return;}
var chr=getChar(e);if(chr===null){return;}
if(chr<'0'||chr>'9'){return false;}},allOnlySelf:function(el,action){var position=doGetCaretPosition(el),regEx=/[.]/g,len=0;if(action==='en'){regEx=/[а-яёъА-ЯЁЪ]/g;}else if(action==='ru'){regEx=/[a-zA-Z]/g;}
len=el.value.match(regEx);len=len!==null?len.length:0;el.value=el.value.replace(regEx,'');setCaretPosition(el,position-len);},translateCHPU:function(el){var A=[],value,pos,CHAR,i;A["Ё"]="YO";A["Й"]="I";A["Ц"]="TS";A["У"]="U";A["К"]="K";A["Е"]="E";A["Н"]="N";A["Г"]="G";A["Ш"]="SH";A["Щ"]="SCH";A["З"]="Z";A["Х"]="H";A["Ъ"]="";A["ё"]="yo";A["й"]="i";A["ц"]="ts";A["у"]="u";A["к"]="k";A["е"]="e";A["н"]="n";A["г"]="g";A["ш"]="sh";A["щ"]="sch";A["з"]="z";A["х"]="h";A["ъ"]="";A["Ф"]="F";A["Ы"]="I";A["В"]="V";A["А"]="A";A["П"]="P";A["Р"]="R";A["О"]="O";A["Л"]="L";A["Д"]="D";A["Ж"]="ZH";A["Э"]="E";A["ф"]="f";A["ы"]="i";A["в"]="v";A["а"]="a";A["п"]="p";A["р"]="r";A["о"]="o";A["л"]="l";A["д"]="d";A["ж"]="zh";A["э"]="e";A["Я"]="YA";A["Ч"]="CH";A["С"]="S";A["М"]="M";A["И"]="I";A["Т"]="T";A["Ь"]="";A["Б"]="B";A["Ю"]="YU";A["я"]="ya";A["ч"]="ch";A["с"]="s";A["м"]="m";A["и"]="i";A["т"]="t";A["ь"]="";A["б"]="b";A["ю"]="yu";A[" "]="_";A["/"]="_";A["&"]="and";value=el.value;pos=doGetCaretPosition(el);value=value.split('');for(i=0;i<value.length;i+=1){CHAR=value[i];if(A[CHAR]!==undefined){value[i]=A[CHAR];if(A[CHAR].length>1){pos+=A[CHAR].length-1;}}}
el.value=value.join('').toLowerCase();setCaretPosition(el,pos);}};$(document).on('input',element,function(){var value=this.value,translateCHPU=this.hasAttribute('tsanslateCHPU'),onlyRu=this.hasAttribute('onlyRu'),onlyEn=this.hasAttribute('onlyEn');if(translateCHPU){lib.translateCHPU(this);}
if(onlyRu){lib.allOnlySelf(this,'ru');}
if(onlyEn){lib.allOnlySelf(this,'en');}}).on('keypress',element,function(event){var onlyNumbers=this.hasAttribute('onlyNumbers');if(onlyNumbers){return lib.onlyNumbers(event);}});}());(function(){'use strict';$(document).on('input','[mask]',function(){var i,format='##.##.####',delim='#',reg=/[A-Za-zА-ЯЁа-яё0-9]/,el=this,value=el.value,pos=doGetCaretPosition(el);if(!value.length){return;}
if(this.getAttribute('mask')!==''){format=this.getAttribute('mask');}
format=format.split('');value=value.split('');if(value.length>format.length){value=value.splice(0,format.length);}
for(i=0;i<value.length;i+=1){if(!reg.test(value[i])){value.splice(i,1);}}
for(i=0;i<value.length;i+=1){if(format[i]!==delim){value.splice(i,0,format[i]);if(i+1===pos){pos+=1;}}}
el.value=value.join('');setCaretPosition(el,pos);});}());(function(){'use strict';$(document).on('mouseover','[help]',function(){var text,node,isInit=this.helpInit,pos=$(this).offset();text=this.getAttribute('help');node=document.createElement('SPAN');node.className='help-block';document.body.appendChild(node);node.innerHTML=text;this.helpInit=node;this.helpInit.style.top=(pos.top-(this.helpInit.offsetHeight+7))+'px';this.helpInit.style.left=pos.left+'px';}).on('mouseout','[help]',function(){var isInit=this.helpInit;if(isInit){this.helpInit.parentNode.removeChild(this.helpInit);}});}());(function(){'use strict';var $window=$(window),widnowHeight=$window.height(),windowWidth=$window.width();$window.resize(function(){widnowHeight=$window.height();windowWidth=$window.width();});var hideDropdown=function(){$('.dropdown > .dropdown-block').css({'display':'none','z-index':1});},showDropdown=function(el){hideDropdown();var documentHeight=$(document).height(),windowSctollTop=$window.scrollTop(),$dropdown=$(el.parentNode),$block=$dropdown.children('.dropdown-block');$block[0].style.display='block';$block[0].style.zIndex=9;var dropdownPosition=$dropdown.offset(),blockHeight=$block.innerHeight(),blockWidth=$block.innerWidth(),topPosition='dropdown__bottom',leftPosition='dropdown__right';var isTop=(dropdownPosition.top+blockHeight>documentHeight)||(dropdownPosition.top-blockHeight-10<0);var isLeft=false;if(dropdownPosition.left+blockWidth>windowWidth){isLeft=true;if(dropdownPosition.left-blockWidth<0){isLeft=false;}}
if(isTop){$dropdown.addClass(topPosition);}else{$dropdown.removeClass(topPosition);}
if(isLeft){$dropdown.addClass(leftPosition);}else{$dropdown.removeClass(leftPosition);}
$dropdown.find('[autofocus]').focus();};$(document).on('mouseup','.dropdown-name',function(){showDropdown(this);}).on('mouseup',function(event){var el=event.target;if($(el).hasClass('dropdown')||$(el).parents('.dropdown').length){return;}
hideDropdown();}).on('keyup',function(event){if(event.keyCode===27){hideDropdown();}}).on('dropdown-close',function(){hideDropdown();});}());(function(){'use strict';var callStack=[],resize=function(){$('.popup:visible').each(function(){var $e=$(this),wHeight=$(window).height(),pHeight=$e.innerHeight();if(pHeight<wHeight-40){$e.css('margin-top',(wHeight/2)-(pHeight/2));}else{$e.css({'margin-top':''});}});},eventCallStack=function(action,$popup,role){var i,len=callStack.length;for(i=0;i<len;i+=1){if(callStack[i].role&&callStack[i].role===role){if(callStack[i][action]){callStack[i][action]($popup);resize();}}}},close=function(){$('.popup-alpha').remove();$('.popup:visible').each(function(){if($(this).parent('.box-popup')){$(this).hide().unwrap();eventCallStack('close',$(this),this.getAttribute('role'));}});$('body').css('overflow','auto');};LIB.popup=function(role){if(role){var $popupList=$('.popup'),$body=$('body'),$popup=$popupList.closest('[role='+role+']:first'),$close,$alpha,$wrap,wHeight,pHeight;if($popup.length){$alpha=$('<div class="popup-alpha"/>');$wrap=$('<div class="box-popup"/>');$popup.wrap($wrap);$body.append($alpha);$body.css('overflow','hidden');eventCallStack('open',$popup,role);wHeight=$(window).height();pHeight=$popup.height();if(pHeight<wHeight-40){$popup.css('margin-top',(wHeight/2)-(pHeight/2));}
$popup.show();$popup.find('[popup-close]').on('mouseup.popup-close',close);$wrap.find('[autofocus]').focus();return $popup;}}else{close();}};$(window).resize(function(){resize();});$(document).on('mouseup.popup','[popup]',function(event){LIB.popup(this.getAttribute('popup'));}).on('mouseup.popup-close',function(event){var el=$(event.target);if(event.target.tagName){if(el.hasClass('popup')||el.parents('.popup').length||event.target.hasAttribute('popup')){return;}}
close();}).on('keyup.popup',function(event){if(event.keyCode===27){close();}});$.fn.popupResize=resize;$.fn.popup=function(param){callStack.push(param);};}());var Spin=(function(){'use strict';var lib={};lib.set=function($element,text){var $spin=$('<div class="spinner"></div>'),template=['<span class="spinner-block">'];if(text!==undefined){template.push('<span class="spinner-text">'+text+'</span>');}
template.push('<span class="spinner-line"></span></span>');$spin.append(template.join(''));$element.children().hide();$element.append($spin);};lib.edit=function($element,text){$element.find('.spinner-text').text(text);};lib.remove=function($element,option){$element.find('.spinner').fadeTo(300,0,function(){$(this).remove();});$element.children().fadeTo(300,1);};return lib;}());var Notification=(function(){'use strict';var lib={},mes=[],mesIndex=0,opts={message:'',flag:'',show:false,hide:true},show=function(list,index){var c=0,len=list.length-1,init=function(el){var clear=setTimeout(function(){Notification.remove(el.data('index'));},3000);el.off('mouseover.notif').on('mouseover.notif',function(){clearTimeout(clear);}).off('mouseout.notif').on('mouseout.notif',function(){init(el);});};list.each(function(k,e){$(this).fadeTo(50+(k+1)*100,1,function(){if(list.eq(len-k).data('hide')===true){init(list.eq(len-k));}});});};lib.set=function(option){var template=$('<div class="notification-item"/>');option=$.extend({},opts,option);template.addClass('notification-item__'+option.flag);template.html(option.message);mes.push({element:template,index:mesIndex+=1,hide:option.hide,option:option});if(option.show){Notification.show();}
return template;};lib.show=function(){var i,len=mes.length,template,event=function(){Notification.remove(this.getAttribute('data-index'));};if($('.notification').length<1){$('body').append('<div class="notification"/>');}
template=$('.notification');for(i=0;i<len;i+=1){mes[i].element.on('click',event);mes[i].element.attr('data-index',mes[i].index);mes[i].element.attr('data-hide',mes[i].hide);template.prepend(mes[i].element);}
$('body').append(template);show(template.children());};lib.remove=function(index){var i=0,len=mes.length;if(!isNaN(index)){index=parseInt(index,10);var message=false;for(i=0;i<mes.length;i+=1){if(mes[i].index===index){message=mes.splice(i,1);}}
GLOBAL.set('notification',message[0]);$('.notification [data-index='+index+']').fadeTo(300,0,function(){$(this).remove();if($('.notification').children().length<1){$('.notification').remove();}});}};return lib;}());(function(){$(document).on('mouseup','.tab-btn',function(){var $this=$(this),$parent=$this.parents('.tab-box'),$btn=$parent.find('.tab-btn'),$blocks=$parent.find('.tab-block'),index=$btn.index($this);if(!$this.hasClass('active')){$blocks.slideUp(200,function(){}).eq(index).slideDown(200,function(){$blocks.removeClass('active').eq(index).addClass('active');$btn.removeClass('active').eq(index).addClass('active');});}});}());(function(){$(function(){$('form').each(function(){if(this.hasAttribute('watch')&&this.getAttribute('watch')!==''){var $this=$(this),invalid=false;$this.find('input, select, textarea').each(function(){if(!LIB.validate(this))invalid=true;});GLOBAL.set(this.getAttribute('watch'),{is:!invalid,form:this});}});});$(document).on('input','form',function(){var $this=$(this),invalid=false;if(this.hasAttribute('watch')&&this.getAttribute('watch')!==''){$this.find('input, select, textarea').each(function(){if(!LIB.validate(this))invalid=true;});GLOBAL.set(this.getAttribute('watch'),{is:!invalid,form:this});}}).on('submit','form',function(event){var $this=$(this),invalid=false,data={},elements=[];$this.find('input, select, textarea').each(function(){$(this).trigger('input').trigger('blur');if($(this).hasClass('invalid'))invalid=true;elements.push(this);data[this.name]=this.value;});if(invalid){var error=this.hasAttribute('error')&&this.getAttribute('error')!==''?this.getAttribute('error'):false;if(error!==false){GLOBAL.set(error,{data:data,elements:elements,form:$this});}
event.preventDefault();}else{var action=this.hasAttribute('action')&&this.getAttribute('action')!==''?this.getAttribute('action'):'',method=(this.hasAttribute('method')&&this.getAttribute('method')!=='')?this.getAttribute('method'):'POST',ajaxSuccess=this.hasAttribute('ajax-success')&&this.getAttribute('ajax-success')!==''?this.getAttribute('ajax-success'):false,submit=this.hasAttribute('submit')&&this.getAttribute('submit')!==''?this.getAttribute('submit'):'POST',beforeSend=this.hasAttribute('before-send')&&this.getAttribute('before-send')!==''?this.getAttribute('before-send'):false,send=this.hasAttribute('send')&&this.getAttribute('send')!==''?this.getAttribute('send'):false;if(beforeSend!==false){GLOBAL.set(beforeSend,{data:data,elements:elements,form:$this});}
if(this.hasAttribute('ajax')){$.ajax({url:action,type:method,data:data,success:function(response){if(ajaxSuccess)GLOBAL.set(ajaxSuccess,{data:data,response:response,elements:elements,form:$this});}});event.preventDefault();}
if(send)GLOBAL.set(send,1);}})}());(function(){$.fn.ctrlSelect=function(){this.each(function(){var $this=$(this),$option=$this.children('option'),$list=$('<ul class="btn-select"/>'),checkName=false;$option.each(function(){var li=$('<li/>');li.text(this.innerHTML);$list.append(li);if($(this).is(':checked')){checkName=this.innerHTML;}});if(checkName===false){checkName=$option.eq(0).text()}
if(!$this.parent('.js-btn-select').length){$this.wrap('<span class="btn js-btn-select"/>');}
var parent=$this.parent();var $cloneUl=$list.clone();$('body').append($cloneUl);$cloneUl.css('float','left');$list.width($cloneUl.width());$cloneUl.remove();if(!parent.find('.btn-in').length){parent.append($('<span class="btn-in btn-in__first">'+checkName+'</span>'));parent.append($('<i class="btn-in btn-tail btn-in__last" />'));parent.append($list);}else{parent.find('.btn-select').remove();parent.find('.btn-select');parent.append($list);}
$this.hide();});};var hideSelect=function(){$('.js-btn-select').removeClass('btn__active').children('ul').hide();};$(document).on('mouseup','.js-btn-select',function(){hideSelect();var $this=$(this),$select=$this.find('select'),$option=$select.find('option'),$ul=$this.children('ul'),$li=$ul.children('li');$ul.show();$li.off('click').on('click',function(){var index=$li.index($(this)),value=$option.eq(index).val();$select.val(value);$option.attr('selected',false).eq(index).attr('selected',true);if($select.attr('watch')&&$select.attr('watch')!==''){GLOBAL.set($select.attr('watch'),{value:value,select:$select,block:$this});}
$this.children('.btn-in.btn-in__first').text($(this).text());hideSelect();});$this.addClass('btn__active');}).on('mouseup',function(event){if(!$(event.target).closest('.js-btn-select').length){hideSelect();}});$(function(){$('.ctrl-select').ctrlSelect();});}());(function(){LIB.sort=function($list,callback){$list.off('mousedown.sort').on('mousedown.sort',function(event){var t=this,baseX=event.pageX,baseY=event.pageY,$this=$(t),$body=$('body'),list=[],$copy,$rezerv;$body.addClass('no-select');$body.css('cursor','move');$(document).off('mousemove.sort').on('mousemove.sort',function(event){var x=event.pageX,y=event.pageY;if(baseX===x&&baseY!==y)return;if(!$copy){$rezerv=$this.clone();$copy=$this.clone();$this.after($copy);$copy.addClass('js-pointer').css({background:'rgba(250,125,125,0.9)'});$this.remove();$list=$list.parent().children(t.tagName.toLowerCase());$list.each(function(){var $t=$(this),pos=$t.offset();list.push({top:pos.top,left:pos.left,width:$t.width(),height:$t.height()});});}
var i=0,len=list.length;for(;i<len;i++){if(y>list[i].top&&y<list[i].top+list[i].height){var del=list[i].top+(list[i].height/2);if(y<del){$list.eq(i).before($copy);}else{$list.eq(i).after($copy);}}}}).off('mouseup.sort').on('mouseup.sort',function(){$(document).off('mousemove.sort').off('mouseup.sort');$body.removeClass('no-select');$body.css('cursor','auto');if($copy&&$copy.length&&$rezerv&&$rezerv.length){$copy.after($rezerv);$copy.remove();$list=$list.parent().children(t.tagName.toLowerCase());if(is(callback,'Function')){callback($list);}
LIB.sort($list,callback);}});});};}());(function(){$(document).on('mouseup','.ctrl-box',function(event){event.stopPropagation();$(this).find('input:visible').eq(0).focus();});}());
var Datepicker=function(){var NAMESPACE='datepicker',CLASS_DATEPICKER='datepicker',CLASS_DATEPICKER_HEADER='datepicker-header',CLASS_DATEPICKER_BLOCK='datepicker-block',CLASS_DATEPICKER_LEFT_BUTTON='datepicker-left',CLASS_DATEPICKER_RIGHT_BUTTON='datepicker-right',CLASS_DATEPICKER_TITLE='datepicker-title',SELF_DAY=new Date,PERIOD=[],PARENT=false,CURRENT=new Date(SELF_DAY.getFullYear(),SELF_DAY.getMonth(),SELF_DAY.getDate()),CURRENT_DATE=new Date(SELF_DAY.getFullYear(),SELF_DAY.getMonth(),SELF_DAY.getDate()),lib={month_names:['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],month_namesGenitive:['Января','Февраля','Марта','Апреля','Мая','Июня','Июля','Августа','Сентября','Октября','Ноября','Декабря'],abbreviation:['Янв','Февр','Март','Апр','Май','Июнь','Июль','Авг','Сент','Окт','Нояб','Дек'],formatAlias:['d','j','F','m','M','n','Y','y'],formatInput:'j.n.Y',formatOutput:'d.m.Y'};lib.dateToString=function(format,date){var i=0,len=format.length,result=[],day=date.getDate(),month=date.getMonth()+1,year=date.getFullYear();for(;i<len;i++){if(inArray(lib.formatAlias,format[i])){switch(format[i]){case'd':result.push((day<10)?'0'+day:day);break;case'j':result.push(day);break;case'F':result.push(lib.month_namesGenitive[month-1]);break;case'm':result.push((month<10)?'0'+month:month);break;case'M':result.push(lib.abbreviation[month-1]);break;case'n':result.push(month);break;case'Y':result.push(year);break;case'y':result.push((''+year).substring(2));break;}}else{result.push(format[i]);}}
return result.join('');};lib.stringToDate=function(format,string){var i=0,len=string.length,num='',date=[];for(;i<len;i++){if(!isNaN(string[i])){num+=string[i];}else{date.push(num);num='';}}
if(num!==''){date.push(num);}
i=0;len=format.length;var result={},count=0;for(;i<len;i++){if(inArray(lib.formatAlias,format[i])){switch(format[i]){case'd':case'j':if(!date[count])return false;result.day=date[count];count++;break;case'F':case'M':case'm':case'n':if(!date[count])return false;result.month=date[count];count++;break;case'y':case'Y':if(!date[count])return false;result.year=date[count];count++;break;}}}
return new Date(result.year,result.month-1,result.day);};lib.getDays=function(year,month){var i,days=[],date=new Date(year,month),backDate=new Date(date.getFullYear(),date.getMonth()-1);lib.current=new Date(year,month);for(i=0;i<lib.getDay(date);i+=1){days.push({day:lib.daysInMonth(backDate)-(lib.getDay(date)-i-1),month:backDate.getMonth(),year:backDate.getFullYear()});}
while(date.getMonth()===month){days.push({day:date.getDate(),month:date.getMonth(),year:date.getFullYear()});date.setDate(date.getDate()+1);}
if(lib.getDay(date)!==0){for(i=lib.getDay(date);i<7;i+=1){days.push({day:date.getDate(),month:date.getMonth(),year:date.getFullYear()});date.setDate(date.getDate()+1);}}
return{year:year,month:month,days:days};};lib.getDay=function(date){var day=date.getDay();if(day===0){day=7;}
return day-1;};lib.daysInMonth=function(date){return 33-new Date(date.getFullYear(),date.getMonth(),33).getDate();};lib.createCalendar=function(year,month){var i,item,days=lib.getDays(year,month),eLeftButton=document.createElement('SPAN'),eRightButton=document.createElement('SPAN'),eTitle=document.createElement('SPAN'),eBox=document.createElement('DIV'),eHeader=document.createElement('DIV'),eBlock=document.createElement('DIV');eBox.className=CLASS_DATEPICKER;eHeader.className=CLASS_DATEPICKER_HEADER;eBlock.className=CLASS_DATEPICKER_BLOCK;eBox.appendChild(eHeader);eBox.appendChild(eBlock);eTitle.innerHTML=lib.month_names[days.month]+' '+days.year;eTitle.className=CLASS_DATEPICKER_TITLE;eLeftButton.className=CLASS_DATEPICKER_LEFT_BUTTON;eRightButton.className=CLASS_DATEPICKER_RIGHT_BUTTON;eHeader.appendChild(eLeftButton);eHeader.appendChild(eTitle);eHeader.appendChild(eRightButton);for(i=0;i<days.days.length;i+=1){item=document.createElement('DIV');item.innerHTML=days.days[i].day;item.setAttribute('year',days.days[i].year);item.setAttribute('month',days.days[i].month);item.setAttribute('day',days.days[i].day);if(!lib.isDisabled(days.days[i],item)){lib.isCurrent(days.days[i],item);}
eBlock.appendChild(item);}
eBox[NAMESPACE]=lib
return eBox;};lib.isDisabled=function(item,node){var isDisable=false,itemPeriod={},i=0,len=PERIOD.length,itemStamp=(new Date(item.year,item.month,item.day)).getTime();for(;i<len;i++){var period=PERIOD[i];if(period.form&&period.to){if(itemStamp>=period.from.getTime()&&itemStamp<=period.to.getTime()){itemPeriod=period;isDisable=true;break;}}else if(!period.form){if(itemStamp<=period.to.getTime()){itemPeriod=period;isDisable=true;break;}}else{if(itemStamp>=period.to.getTime()){itemPeriod=period;isDisable=true;break;}}}
if(isDisable&&node){node.className+=' '+NAMESPACE+'-disable';if(itemPeriod.help){node.setAttribute('help',itemPeriod.help);}}
return isDisable;};lib.isCurrent=function(item,node){var day=CURRENT_DATE.getDate(),month=CURRENT_DATE.getMonth(),year=CURRENT_DATE.getFullYear(),isCurrent=false;isCurrent=(item.day===day&&item.month===month&&item.year===year);if(node&&isCurrent){node.className+=NAMESPACE+'_current_day';}
return isCurrent;};lib.appendDropdown=function(node){$(node).parents('.dropdown:first').children('.dropdown-block').html(lib.createCalendar(CURRENT.getFullYear(),CURRENT.getMonth())).append('<i class="dropdown-tail"/>');};lib.change=function(node){if(node.hasAttribute(NAMESPACE+'-format')){lib.formatOutput=node.getAttribute(NAMESPACE+'-format');}
if(node.tagName==='INPUT'||node.tagName==='TEXTAREA'){node.value=lib.dateToString(lib.formatOutput,CURRENT_DATE);}else{node.innerHTML=lib.dateToString(lib.formatOutput,CURRENT_DATE);}
lib.appendDropdown(node);if(node.getAttribute(NAMESPACE)!==''){GLOBAL.set(node.getAttribute(NAMESPACE),node);}};lib.init=function($elements,isParent){var node;if($elements&&isParent){node=$elements.find('['+NAMESPACE+']');}else if($elements){node=$elements;}else{node=$('['+NAMESPACE+']');}
node.each(function(){if(!this.hasAttribute(NAMESPACE))return;if(this.getAttribute(NAMESPACE)!==''){GLOBAL.set(this.getAttribute(NAMESPACE),this);}
if(this.getAttribute(NAMESPACE+'-parent')){GLOBAL.watch(this.getAttribute(NAMESPACE+'-parent'),function(node){PARENT=node;});}
if(this.getAttribute(NAMESPACE+'-period')){GLOBAL.watch(this.getAttribute(NAMESPACE+'-period'),function(periods){if(!is(periods,'Array'))return;PERIOD=[];var i=0,len=periods.length;for(;i<len;i++){if(!is(periods[i],'Object'))continue;if(!periods[i].from&&!periods[i].to)continue;var newPeriod={};if(periods[i].from)newPeriod.from=lib.stringToDate(lib.formatInput,periods[i].from);if(periods[i].to)newPeriod.to=lib.stringToDate(lib.formatInput,periods[i].to);if(periods[i].help)newPeriod.help=periods[i].help;PERIOD.push(newPeriod);}});}
var self=this,dropdownBlock=$('<span class="dropdown-block"/>');dropdownBlock.append($('<i class="dropdown-tail"/>'));$(this).wrap('<span class="dropdown" />');$(this).parent().append(dropdownBlock);$(this).wrap('<span class="dropdown-name"/>');lib.change(this);dropdownBlock.on('mouseup.'+NAMESPACE,'.'+CLASS_DATEPICKER_LEFT_BUTTON+', .'+CLASS_DATEPICKER_RIGHT_BUTTON,function(event){event.stopPropagation();var year=CURRENT.getFullYear(),month=CURRENT.getMonth();if(this.className.indexOf(CLASS_DATEPICKER_LEFT_BUTTON)>-1){if(month-1<0){year-=1;month=11;}else{month-=1;}}else{if(month+1>11){year+=1;month=0;}else{month+=1;}}
CURRENT=new Date(year,month);lib.appendDropdown(self);}).on('mouseup.'+NAMESPACE,'.'+CLASS_DATEPICKER_BLOCK+' div:not(.'+NAMESPACE+'-disable'+')',function(event){event.stopPropagation();year=this.getAttribute('year')*1,month=this.getAttribute('month')*1,day=this.getAttribute('day')*1;CURRENT_DATE=new Date(year,month,day);lib.change(self);$(document).trigger('dropdown-close');});});};return lib;}();$(function(){Datepicker.init();});
$(function(){'use strict';errorResize();if($.fn.ckeditor){$('.editor').ckeditor();}});GLOBAL.watch('notification',function(message){if(message&&message.option){$.post('',{'action':'clearSystemMessage','id':message.option.key},function(res){});}});$(window).resize(errorResize);function errorResize(){var $errorPage=$('.error-page');if($errorPage.length){var $parentError=$('body'),heightParent=$parentError.height(),heightPage=$errorPage.height();$errorPage.css({marginTop:(heightParent/2)-(heightPage/2)});}}
function spin(text){$('.alpha').show();Spin.set($('.alpha-message'),text||'Подождите идет загрузка');}
function stopSpin(){Spin.remove($('.alpha-message'));$('.alpha').hide();}
$(document).on('input','.header-search input',function(){var value=this.value,block=$(this).parent().children('.header-search-result-block');if(value.length>3){search(value,block);}}).on('keyup','.header-search input',function(event){var value=this.value,block=$(this).parent().children('.header-search-result-block');if(event.keyCode===13&&value.length>0){search(value,block);}
if(value.length>0){$(this).addClass('active');}else{block.slideUp(100);$(this).removeClass('active');}}).on('mouseup',function(event){if($(event.target).closest('.header-search').length)return;$('.header-search-result-block').stop().slideUp(100);});function search(value,block){$.post('',{action:'search',value:value},function(res){var list=document.createElement('UL'),count=0;for(var i=0;i<res.length;i++){var li=addResultSearch(res[i]);list.appendChild(li);count+=res[i].find.length;}
if(count>0){block.html(list);block.slideDown(150);}else{block.html();block.slideUp(150);}});}
function addResultSearch(res){var li=document.createElement('LI'),head=document.createElement('H3'),list=document.createElement('UL');head.innerHTML=res.name;li.appendChild(head)
li.appendChild(list);var max=res.find.length>5?5:res.find.length;for(var i=0;i<max;i++){var item=document.createElement('LI'),name=res.find[i].name?res.find[i].name:'undefiend - '+res.find[i].id,a=document.createElement('A'),block=document.createElement('DIV'),table=document.createElement('TABLE');a.href='?mode=elem&id='+res.find[i].id;a.appendChild(document.createTextNode(name));a.appendChild(block);block.appendChild(table);table.className='table w-big';for(var x in res.find[i]){var el=res.find[i][x],falseBlock=document.createElement('DIV'),tr=document.createElement('TR'),tdName=document.createElement('TD'),tdDesc=document.createElement('TD');falseBlock.innerHTML=el;el=falseBlock.textContent;if(el.length<1)continue;if(el.length>200){el=el.substr(0,200)+'...';}
tdName.appendChild(document.createTextNode(x));tdDesc.appendChild(document.createTextNode(el));tr.appendChild(tdName);tr.appendChild(tdDesc);table.appendChild(tr);}
item.appendChild(a);list.appendChild(item);}
return li;}
GLOBAL.watch('structForm',function(obj){var button=$(obj.form).find('button.btn');if(obj.is){button.removeClass('btn__disable');button.removeAttr('disabled');}else{button.addClass('btn__disable');button.attr('disabled','disabled');}});GLOBAL.watch('beforeSend',function(){spin();});
$(function(){$('.js-edit').on('click',function(){var $this=$(this),$li=$this.parents('li'),$name=$li.find('.name');if(!$this.hasClass('dropdown_name')){var $parent=$this.parents('.ibox'),$form=$parent.find('.js-add').clone();$this.addClass('dropdown_name');$this.wrap('<span class="dropdown"/>');$this.parent().append($form);$form.removeClass('js-add').find('form').append('<input type="hidden" name="id" value="'+$li.data('id')+'"/>');}
$li.find('.btn__positive .btn-in').text('Изменить');$li.find('.inp').val($name.text());});var $tableBlock=$('.js-structTables'),$list=$tableBlock.find('ul > li'),$table=$tableBlock.find('.js-structTable');$list.eq(0).addClass('list-active_item');$table.eq(0).removeClass('dn');$list.on('click',function(){var $this=$(this);if($this.hasClass('list-active_item'))return;$list.removeClass('list-active_item');$this.addClass('list-active_item');$table.addClass('dn');var $selfTable=$table.eq($list.index($this));$selfTable.removeClass('dn');});});$(document).on('mouseup','.js-getNextPage',function(){var $this=$(this),$table=$this.parents('.js-structTable').find('table'),count=this.getAttribute('data-count'),size=this.getAttribute('data-size')*1,table=this.getAttribute('data-table');Spin.set($this.parent());$.post('',{action:'loadTable',count:count,table:table},function(response){response=JSON.parse(response);Notification.set({message:response.message,flag:'good'});Notification.show();var count=0,template=[];template.push('<tr class="not"><th colspan="'+Object.keys(response.result[0]).length+'"><hr/></th></tr>');while(true){if(count==response.result.length){break;}
var obj=response.result[count];template.push('<tr>');template.push('<td><input type="checkbox" name="" value=""/></td>');for(var i in obj){template.push('<td>'+obj[i]+'</td>');}
template.push('<td><i class="icon-pencil"></i><i class="icon-cancel"></i></td>');template.push('</tr>');count++;}
$table.append(template.join(''));$this[0].setAttribute('data-count',response.count);setTimeout(function(){Spin.remove($this.parent());if(size-response.count*1<0){$this.remove();}else{$this.text('еще '+(size-response.count*1))}},500);});});$(document).on('mousedown',function(event){if($(event.target).closest('.js-structTable .editable').length)return;var $editable=$('.js-structTable .editable');if($editable.length){editableRow($editable[0]);$editable.removeClass('editable');$editable.attr('contenteditable',false);}}).on('click','.js-structTable td',function(){if(this.className.indexOf('editable')>-1)return;$('.js-structTable .editable').each(function(){this.className='';this.setAttribute('contenteditable',false);});this.className='editable';this.defaultValue=this.innerHTML;this.setAttribute('contenteditable',true);$(this).focus().off('keydown').on('keydown',function(event){if(event.keyCode===37||event.keyCode===39){var caretPosition=getCaretPosition(this);if(caretPosition===this.innerHTML.length||caretPosition===0){editableRow(this);var $this=$(this),$table=$this.parents('table'),$td=$table.find('td'),index=$td.index($this);if(event.keyCode===37&&caretPosition===0){$td.eq(index-1).trigger('click');}else if(event.keyCode===39&&caretPosition===this.innerHTML.length){$td.eq(index+1).trigger('click');}}}else if(event.keyCode===40||event.keyCode===38){event.preventDefault();editableRow(this);var $this=$(this),$parent=$this.parents('table'),$parentTR=$this.parent(),$tr=$parent.find('tr:not(.not)'),index=$parentTR.children().index($this);if(event.keyCode===38){$tr.eq($tr.index($parentTR)-1).children().eq(index).trigger('click');}else{if($tr.index($parentTR)+5>=$tr.length){$('.js-getNextPage').trigger('mouseup');$tr=$parent.find('tr:not(.not)');}
$tr.eq($tr.index($parentTR)+1).children().eq(index).trigger('click');}}else if(event.keyCode===9){event.preventDefault();editableRow(this);var $this=$(this),$table=$this.parents('table'),$td=$table.find('td'),index=$td.index($this);$td.eq(index+1).trigger('click');}else if(event.keyCode===13){event.preventDefault();$(document).trigger('mousedown');}});}).on('keyup',function(event){if(event.keyCode===27){$('.js-structTable .editable').each(function(){this.className='';this.setAttribute('contenteditable',false);});}});function editableRow(t){var defValue=t.defaultValue,value=t.innerHTML;if(value!==defValue){var $row=$(t).parent().children('td'),action={action:'editRowInTable'},loadSpin=setTimeout(function(){spin();},300);action.table=$('.js-structTables .list-active_item').data('table');action.row=[];$row.each(function(){action.row.push({name:this.getAttribute('data-name'),defValue:this.defaultValue?this.defaultValue:this.innerHTML,newValue:this.innerHTML});this.defaultValue=this.innerHTML;});$.post('',action,function(res){clearTimeout(loadSpin);stopSpin();Notification.set({message:res,flag:'good'});Notification.show();});}}
$(function(){var $list=$('.project-list li');if(!$list.length)return;LIB.sort($('.js-sortable-list li'),function($list){spin('Подождите идет обработка');var action={action:'sortElem',id:[]};$list.each(function(){action.id.push(this.getAttribute('data-id'));});$.post('',action,function(res){window.location=window.location.href;})});$('.project-filter-objects span').each(function(){var code=this.getAttribute('data-code'),count=0;if(code==0){count=$list.length;}else{$list.each(function(){if(this.getAttribute('data-code')===code){count++;}});}
if(count){this.innerHTML+=' <sup>'+count+'</sup>';}else{this.style.display='none';}}).on('mouseup',function(){var $this=$(this),$butten=$this.parent().children('span');if(!$this.hasClass('current')){$butten.removeClass('current');$this.addClass('current');$list.each(function(){if($this.data('code')===0){this.style.display='block';}else{if(this.getAttribute('data-code')===$this.data('code')){this.style.display='block';}else{this.style.display='none';}}});}});$('.js-projectDetailItemShow').hover(function(){var position=$(this).offset(),$block=$(this).parents('li').find('.js-projectDetailItem');if(position.top-$block.innerHeight()<=0){$block.css({'bottom':'auto','top':'100%','margin-top':'10px'})}
$block.show()},function(){$(this).parents('li').find('.js-projectDetailItem').hide()});var key={ctrl:false,shift:false},lastItem=false,X,Y,$body=$('body'),allocation=false,items=[];$(document).on('keydown',function(event){var k=event.which;if(k===91||k===93||k===17){key.ctrl=true;}
if(k===16){key.shift=true;}}).on('keyup',function(){var k=event.which;if(k===91||k===93||k===17){key.ctrl=false;}
if(k===16){key.shift=false;}}).on('mouseup','.project-list li',function(event){var $list=$('.project-list li'),$this=$(this);if(key.ctrl){$this.toggleClass('active');}else if(key.shift&&lastItem){var lastIndex=$list.index(lastItem),selfIndex=$list.index($this),start=(lastIndex>selfIndex)?selfIndex:lastIndex,end=(lastIndex>selfIndex)?lastIndex:selfIndex;while(true){if(start>end)break;$list.eq(start).addClass('active');start++;}}else{$list.removeClass('active');$this.addClass('active');}
if($this.hasClass('active')){lastItem=$this}
GLOBAL.set('isSelectItem',$list);}).on('mouseup','.js-projectEvent',function(){var data={action:this.getAttribute('action'),parent:GLOBAL.get('page').id,id:[]};spin('Подождите');$('.project-list li.active').each(function(){data.id.push(this.getAttribute('data-id')*1);});$.post('',data,function(response){window.location=window.location.href;});}).on('click','.spin',function(){spin(this.getAttribute('data-spiner'));});GLOBAL.watch('isSelectItem',function($list){if($list.is('.active')){$('.js-projectEvent').removeClass('disable');}else{$('.js-projectEvent').addClass('disable');}});});
$(function(){var $list=$('.object-list');if(!$list.length)return;var add=function(is){$.post('',{action:'getItemObject',index:$list.children().length},function(respons){$list.append(respons);$('.ctrl-select').ctrlSelect();$list=$('.object-list');var $item=$list.children(),count=$item.length-1;$item.each(function(key,val){this.style.zIndex=count-key;});if(is){loadParam($item.eq(0).find('.js-setting'),'',count);}});},loadParam=function($block,value,key){$.post('',{action:'getGist',type:value,key:key},function(respons){console.log(respons)
$block.empty().append(respons);$('.ctrl-select',$block).ctrlSelect();});}
GLOBAL.watch('objectType',function(obj){var parent=obj.block.parents('.js-object-item');loadParam(parent.find('.js-setting'),obj.value,$list.children().index(parent));});if($list.children().length<1){add(true);}
$(document).on('click','.js-showSetting',function(){var $this=$(this),$li=$this.parents('li'),$setting=$li.find('.js-setting');if($this.hasClass('active')){$setting.slideUp(300);$this.removeClass('active');}else{$setting.slideDown(300);$this.addClass('active');}});$('.js-add').click(add);});$(document).on('keydown','.js-param-list div.inp',function(event){if(event.keyCode===13){event.preventDefault();var divValue=this.innerHTML,$parent=$(this).parents('.js-param-list'),$inp=$parent.find('input.inp'),$list=$parent.find('ul'),inputValue=$inp.val(),obj=[];if(inputValue!==''){if(json=JSON.parse(inputValue)){obj=json;}}
obj.push(divValue);$inp.val(JSON.stringify(obj));$list.append('<li>'+divValue+'</li>');this.innerHTML='';}}).on('mouseup','.js-param-list li',function(event){var $this=$(this),$parent=$this.parents('.js-param-list'),$list=$parent.find('ul li'),$inp=$parent.find('input.inp'),index=$list.index($this),value=$inp.val(),json;if(json=JSON.parse(value)){if(json[index]){json.splice(index,1);}}
$this.remove();$inp.val(JSON.stringify(json));});$(document).on('mouseup','.js-object-icon-list .object-icon-list i',function(){var $this=$(this),$listIcon=$this.parent().children(),$I=$('.js-object-icon i'),$input=$('.js-object-icon-input'),cls=this.getAttribute('data-class');$I.attr('class',cls);$input.val(cls);$listIcon.removeClass('active');$this.addClass('active');LIB.popup();});$(document).on('mouseup','.js-removeItem',function(){var $li=$(this).parents('li'),$list=$li.parent().children();if($list.length>1){$li.remove();}});
$(document).on('click','.js-user-list',function(){var login=this.getAttribute('data-login'),access=this.getAttribute('data-access'),id=this.getAttribute('data-id'),$popup=LIB.popup('userSetting'),$login=$popup.find('input[name=name]'),$id=$popup.find('input[name=id]'),$select=$popup.find('select[name=access]');$login.val(login);$id.val(id);$select.children('option').each(function(k,v){if(this.value===access){$select.parent().find('.btn-in__first').text(this.innerHTML);return;}});$login.trigger('input');});
$(document).on('click','.js-createBuckUp',function(event){spin();$.post('',{action:'buckup'},function(res){GLOBAL.set('backupCount',0);GLOBAL.set('backupSize',res['table'].length);for(var i=0;i<res['table'].length;i++){$.post('',{action:'buckup',table:res['table'][i],stamp:res.stamp},function(){GLOBAL.set('backupCount',GLOBAL.get('backupCount')+1);});}});GLOBAL.watch('backupCount',function(){if(GLOBAL.get('backupCount')===GLOBAL.get('backupSize')){stopSpin();window.location=window.location.href;}});});
$(function(){var block=$('.js-widget-li-ru');if(!block.length)return;$.post('',{'action':'li_count'},function(res){if(res['LI_error']){block.html('Щечик <b>liveinternet</b> не найден');}else{var template=['Количество просмотров за месяц: '+res['LI_month_hit'],'Количество посетителей за месяц: '+res['LI_month_vis'],'Количество просмотров за неделю: '+res['LI_week_hit'],'Количество посетителей за неделю: '+res['LI_week_vis'],'Количество просмотров за 24 часа: '+res['LI_day_hit'],'Количество посетителей за 24 часа: '+res['LI_day_vis'],'Количество просмотров за сегодня: '+res['LI_today_hit'],'Количество посетителей за сегодня: '+res['LI_today_vis'],'Просмотры посетителей на данный момент (онлайн): '+res['LI_online_hit'],'Количество посетителей на сайте в данный момент (онлайн): '+res['LI_online_vis']];block.html(template.join('<br/>'));}});});